package com.avianto.back;

import static com.avianto.back.ApiDtos.*;
import jakarta.transaction.Transactional;
import org.springframework.cache.annotation.*;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

@Service
@Transactional
public class ApiService {
  private final DataRepository db;
  public ApiService(DataRepository db) { this.db=db; }
  private Map<String,Object> p() { return new HashMap<>(); }
  private UUID actorId() { try { return UUID.fromString(SecurityContextHolder.getContext().getAuthentication().getName()); } catch(Exception e) { return null; } }
  AppUser actor() { UUID id=actorId(); return id==null?null:db.get(AppUser.class,id); }
  void audit(String module,String action,String text) { Auditoria a=new Auditoria(); a.usuario=actor(); a.modulo=module; a.accion=action; a.descripcion=text; db.persist(a); }
  private void deleted(BaseEntity e) {
    if(e instanceof Cliente x) x.activo=false;
    if(e instanceof Motovehiculo x) x.activo=false;
    if(e instanceof ItemCatalogo x) x.activo=false;
    if(e instanceof MarcaMoto x) x.activo=false;
    if(e instanceof CategoriaCatalogo x) x.activo=false;
    if(e instanceof AppUser x) x.activo=false;
    e.deletedAt=Instant.now(); e.deletedBy=actorId();
  }
  private <T> PageResponse<T> page(String from, String where, String count, Map<String,Object> ps, int page,int size,String sort,String dir, Function<Object,T> mapper) {
    if(page<0 || !(size==10||size==20||size==50||size==100)) throw new BusinessException(400,"Paginación inválida");
    String order=" order by e."+sort+" "+("DESC".equalsIgnoreCase(dir)?"DESC":"ASC");
    List<T> content=db.list("select e "+from+where+order,Object.class,ps,page,size).stream().map(mapper).toList();
    long total=db.count("select count(e) "+count+where,ps); return new PageResponse<>(content,page,size,total,(int)Math.ceil(total/(double)size),sort,"DESC".equalsIgnoreCase(dir)?"DESC":"ASC");
  }
  private String sortable(String requested, Set<String> allowed, String fallback) { return allowed.contains(requested)?requested:fallback; }
  private String active(boolean includeDeleted) { return includeDeleted?"":" and e.deletedAt is null"; }

  public PageResponse<ClientResponse> clients(String q,Boolean activo,boolean deleted,int page,int size,String sort,String dir) { Map<String,Object> ps=p(); String w=" where 1=1"+active(deleted); if(q!=null&&!q.isBlank()){w+=" and (lower(e.nombre) like :q or lower(coalesce(e.documento,'')) like :q)";ps.put("q","%"+q.toLowerCase()+"%");} if(activo!=null){w+=" and e.activo=:activo";ps.put("activo",activo);} return page("from Cliente e",w,"from Cliente e",ps,page,size,sortable(sort,Set.of("nombre","createdAt","updatedAt"),"nombre"),dir,x->client((Cliente)x)); }
  public ClientResponse client(UUID id){ return client(db.get(Cliente.class,id)); }
  public ClientResponse createClient(ClientRequest r){ Cliente e=new Cliente(); copy(r,e); db.persist(e);audit("Clientes","CREAR",e.nombre);return client(e); }
  public ClientResponse updateClient(UUID id,ClientRequest r){Cliente e=db.get(Cliente.class,id);copy(r,e);audit("Clientes","EDITAR",e.nombre);return client(e);}
  public void deleteClient(UUID id){Cliente e=db.get(Cliente.class,id); if(db.count("select count(m) from Motovehiculo m where m.cliente.id=:id and m.deletedAt is null",Map.of("id",id))>0)throw new BusinessException(409,"El cliente tiene motos activas");deleted(e);audit("Clientes","ELIMINAR",e.nombre);}
  private void copy(ClientRequest r,Cliente e){e.nombre=r.nombre().trim();e.documento=blank(r.documento());e.telefono=r.telefono().trim();e.email=blank(r.email());e.direccion=blank(r.direccion());e.observaciones=blank(r.observaciones());}
  private ClientResponse client(Cliente e){long motos=db.count("select count(m) from Motovehiculo m where m.cliente.id=:id and m.deletedAt is null",Map.of("id",e.id));long orders=db.count("select count(o) from Pedido o where o.cliente.id=:id and o.deletedAt is null",Map.of("id",e.id));return new ClientResponse(e.id,e.nombre,e.documento,e.telefono,e.email,e.direccion,e.observaciones,e.activo,motos,orders,e.createdAt,e.updatedAt);}

  @Cacheable(value="autocomplete",key="'clients:' + #q") public List<AutocompleteResponse> clientAutocomplete(String q){return db.all("select e from Cliente e where e.deletedAt is null and e.activo=true and (lower(e.nombre) like :q or lower(coalesce(e.documento,'')) like :q) order by e.nombre",Cliente.class,Map.of("q","%"+q.toLowerCase()+"%")).stream().limit(15).map(e->new AutocompleteResponse(e.id,e.nombre,e.documento)).toList();}
  @CacheEvict(value="autocomplete",allEntries=true) void clearAutocomplete() {}

  public PageResponse<MotorcycleResponse> motorcycles(String q,UUID clientId,UUID brandId,Boolean activo,boolean deleted,int page,int size,String sort,String dir){Map<String,Object>ps=p();String w=" where 1=1"+active(deleted);if(q!=null&&!q.isBlank()){w+=" and (lower(e.modelo) like :q or lower(e.patente) like :q)";ps.put("q","%"+q.toLowerCase()+"%");}if(clientId!=null){w+=" and e.cliente.id=:client";ps.put("client",clientId);}if(brandId!=null){w+=" and e.marca.id=:brand";ps.put("brand",brandId);}if(activo!=null){w+=" and e.activo=:activo";ps.put("activo",activo);}return page("from Motovehiculo e join fetch e.cliente join fetch e.marca",w,"from Motovehiculo e",ps,page,size,sortable(sort,Set.of("modelo","patente","createdAt","updatedAt"),"patente"),dir,x->motorcycle((Motovehiculo)x));}
  public MotorcycleResponse motorcycle(UUID id){return motorcycle(db.get(Motovehiculo.class,id));}
  public MotorcycleResponse createMotorcycle(MotorcycleRequest r){Motovehiculo e=new Motovehiculo();copy(r,e);db.persist(e);audit("Motovehículos","CREAR",e.patente);clearAutocomplete();return motorcycle(e);}
  public MotorcycleResponse updateMotorcycle(UUID id,MotorcycleRequest r){Motovehiculo e=db.get(Motovehiculo.class,id);copy(r,e);audit("Motovehículos","EDITAR",e.patente);clearAutocomplete();return motorcycle(e);}
  public void deleteMotorcycle(UUID id){Motovehiculo e=db.get(Motovehiculo.class,id);if(db.count("select count(o) from Pedido o where o.motovehiculo.id=:id and o.deletedAt is null",Map.of("id",id))>0)throw new BusinessException(409,"La moto tiene pedidos activos");deleted(e);audit("Motovehículos","ELIMINAR",e.patente);clearAutocomplete();}
  private void copy(MotorcycleRequest r,Motovehiculo e){Cliente c=db.get(Cliente.class,r.clienteId());MarcaMoto b=db.get(MarcaMoto.class,r.marcaId());if(!c.activo||c.deletedAt!=null||!b.activo||b.deletedAt!=null)throw new BusinessException(409,"Cliente o marca inactiva");e.cliente=c;e.marca=b;e.modelo=r.modelo().trim();e.patente=r.patente().trim().toUpperCase();e.anio=r.anio();e.kilometraje=r.kilometraje();e.observaciones=blank(r.observaciones());}
  private MotorcycleResponse motorcycle(Motovehiculo e){return new MotorcycleResponse(e.id,e.cliente.id,e.marca.id,e.cliente.nombre,e.marca.nombre,e.modelo,e.patente,e.anio,e.kilometraje,e.observaciones,e.activo,e.createdAt,e.updatedAt);}
  @Cacheable(value="autocomplete",key="'motorcycles:' + #q") public List<AutocompleteResponse> motorcycleAutocomplete(String q){return db.all("select e from Motovehiculo e join fetch e.marca where e.deletedAt is null and e.activo=true and (lower(e.modelo) like :q or lower(e.patente) like :q) order by e.patente",Motovehiculo.class,Map.of("q","%"+q.toLowerCase()+"%")).stream().limit(15).map(e->new AutocompleteResponse(e.id,e.patente,e.marca.nombre+" "+e.modelo)).toList();}

  @Cacheable("catalog") public PageResponse<CatalogResponse> catalog(String q,ItemType type,UUID category,Boolean activo,boolean deleted,int page,int size,String sort,String dir){Map<String,Object>ps=p();String w=" where 1=1"+active(deleted);if(q!=null&&!q.isBlank()){w+=" and lower(e.descripcion) like :q";ps.put("q","%"+q.toLowerCase()+"%");}if(type!=null){w+=" and e.tipo=:type";ps.put("type",type);}if(category!=null){w+=" and e.categoria.id=:category";ps.put("category",category);}if(activo!=null){w+=" and e.activo=:activo";ps.put("activo",activo);}return page("from ItemCatalogo e join fetch e.categoria",w,"from ItemCatalogo e",ps,page,size,sortable(sort,Set.of("descripcion","precioBase","createdAt","updatedAt"),"descripcion"),dir,x->catalog((ItemCatalogo)x));}
  public CatalogResponse catalog(UUID id){return catalog(db.get(ItemCatalogo.class,id));}
  @CacheEvict(value="catalog",allEntries=true) public CatalogResponse createCatalog(CatalogRequest r){ItemCatalogo e=new ItemCatalogo();copy(r,e);db.persist(e);price(e,null,e.precioBase);audit("Catálogo","CREAR",e.descripcion);return catalog(e);}
  @CacheEvict(value="catalog",allEntries=true) public CatalogResponse updateCatalog(UUID id,CatalogRequest r){ItemCatalogo e=db.get(ItemCatalogo.class,id);BigDecimal prior=e.precioBase;copy(r,e);if(prior.compareTo(e.precioBase)!=0)price(e,prior,e.precioBase);audit("Catálogo","EDITAR",e.descripcion);return catalog(e);}
  @CacheEvict(value="catalog",allEntries=true) public void deleteCatalog(UUID id){ItemCatalogo e=db.get(ItemCatalogo.class,id);deleted(e);audit("Catálogo","ELIMINAR",e.descripcion);}
  private void copy(CatalogRequest r,ItemCatalogo e){CategoriaCatalogo c=db.get(CategoriaCatalogo.class,r.categoriaId());if(!c.activo||c.deletedAt!=null)throw new BusinessException(409,"Categoría inactiva");e.descripcion=r.descripcion().trim();e.tipo=r.tipo();e.categoria=c;e.precioBase=r.precioBase().setScale(2,RoundingMode.HALF_UP);e.observaciones=blank(r.observaciones());}
  private void price(ItemCatalogo e,BigDecimal old,BigDecimal value){PriceHistory h=new PriceHistory();h.item=e;h.precioAnterior=old;h.precioNuevo=value;h.changedBy=actorId();db.persist(h);audit("Catálogo","PRECIO",e.descripcion+": "+value);}
  private CatalogResponse catalog(ItemCatalogo e){return new CatalogResponse(e.id,e.descripcion,e.tipo,e.categoria.id,e.categoria.nombre,e.precioBase,e.observaciones,e.activo,e.createdAt,e.updatedAt);}
  public List<Map<String,Object>> priceHistory(UUID id){return db.all("select h from PriceHistory h where h.item.id=:id order by h.changedAt desc",PriceHistory.class,Map.of("id",id)).stream().map(h->Map.<String,Object>of("id",h.id,"precioAnterior",h.precioAnterior==null?BigDecimal.ZERO:h.precioAnterior,"precioNuevo",h.precioNuevo,"fecha",h.changedAt)).toList();}
  public List<CatalogResponse> duplicates(String desc){return db.all("select e from ItemCatalogo e where e.deletedAt is null and lower(e.descripcion)=:d",ItemCatalogo.class,Map.of("d",desc.trim().toLowerCase())).stream().map(this::catalog).toList();}

  public PageResponse<OrderResponse> orders(String q,UUID client,String plate,String number,String state,String document,LocalDate from,LocalDate to,boolean deleted,int page,int size,String sort,String dir){Map<String,Object>ps=p();String w=" where 1=1"+active(deleted);if(q!=null&&!q.isBlank()){w+=" and (lower(e.numero) like :q or lower(e.cliente.nombre) like :q)";ps.put("q","%"+q.toLowerCase()+"%");}if(client!=null){w+=" and e.cliente.id=:client";ps.put("client",client);}if(plate!=null){w+=" and lower(e.motovehiculo.patente) like :plate";ps.put("plate","%"+plate.toLowerCase()+"%");}if(number!=null){w+=" and lower(e.numero) like :number";ps.put("number","%"+number.toLowerCase()+"%");}if(state!=null){w+=" and e.estado=:state";ps.put("state",OrderState.of(state));}if(document!=null){try{w+=" and e.documento=:doc";ps.put("doc",DocumentType.valueOf(document));}catch(Exception ex){throw new BusinessException(400,"Documento inválido");}}if(from!=null){w+=" and e.createdAt>=:from";ps.put("from",from.atStartOfDay(ZoneOffset.UTC).toInstant());}if(to!=null){w+=" and e.createdAt<:to";ps.put("to",to.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant());}return page("from Pedido e join fetch e.cliente join fetch e.motovehiculo m join fetch m.marca",w,"from Pedido e",ps,page,size,sortable(sort,Set.of("numero","createdAt","total","updatedAt"),"createdAt"),dir,x->order((Pedido)x));}
  public OrderResponse order(UUID id){return order(db.get(Pedido.class,id));}
  public OrderResponse createOrder(OrderRequest r){Pedido e=new Pedido();copy(r,e);e.numero="P-"+System.currentTimeMillis()+"-"+e.id.toString().substring(0,4).toUpperCase();db.persist(e);audit("Pedidos","CREAR",e.numero);return order(e);}
  public OrderResponse updateOrder(UUID id,OrderRequest r){Pedido e=db.get(Pedido.class,id);if(e.estado==OrderState.PAGADO||e.estado==OrderState.CANCELADO)throw new BusinessException(409,"No puede editarse un pedido finalizado");e.items.clear();copy(r,e);audit("Pedidos","EDITAR",e.numero);return order(e);}
  public void deleteOrder(UUID id){Pedido e=db.get(Pedido.class,id);if(e.estado==OrderState.PAGADO)throw new BusinessException(409,"No puede eliminarse un pedido pagado");deleted(e);audit("Pedidos","ELIMINAR",e.numero);}
  private void copy(OrderRequest r,Pedido e){Cliente c=db.get(Cliente.class,r.clienteId());Motovehiculo m=db.get(Motovehiculo.class,r.motovehiculoId());if(!m.cliente.id.equals(c.id))throw new BusinessException(409,"La moto no pertenece al cliente");if(!c.activo||!m.activo||c.deletedAt!=null||m.deletedAt!=null)throw new BusinessException(409,"Cliente o moto inactivo");e.cliente=c;e.motovehiculo=m;e.documento=r.documento();e.vencimiento=r.vencimiento();e.observaciones=blank(r.observaciones());e.descuentoGlobal=money(r.descuentoGlobal());e.iva=r.documento()==DocumentType.Factura&&r.iva();BigDecimal sum=BigDecimal.ZERO;for(OrderItemRequest line:r.items()){if(line.cantidad().stripTrailingZeros().scale()>0)throw new BusinessException(400,"La cantidad debe ser un número entero");PedidoItem i=new PedidoItem();i.pedido=e;if(line.itemCatalogoId()!=null)i.itemCatalogo=db.get(ItemCatalogo.class,line.itemCatalogoId());i.descripcion=line.descripcion().trim();i.tipo=line.tipo();i.cantidad=line.cantidad();i.precioUnitario=money(line.precioUnitario());i.descuento=money(line.descuento());i.subtotal=money(i.cantidad.multiply(i.precioUnitario).subtract(i.descuento));if(i.subtotal.signum()<0)throw new BusinessException(400,"Descuento de línea inválido");e.items.add(i);sum=sum.add(i.subtotal);}sum=sum.subtract(e.descuentoGlobal);if(sum.signum()<0)throw new BusinessException(400,"Descuento global inválido");e.total=money(e.iva?sum.multiply(new BigDecimal("1.21")):sum);}
  public OrderResponse state(UUID id,StateRequest r){Pedido e=db.get(Pedido.class,id);OrderState next=OrderState.of(r.estado());boolean valid=(e.estado==OrderState.EN_PROCESO&&(next==OrderState.APROBADO||next==OrderState.CANCELADO))||(e.estado==OrderState.APROBADO&&(next==OrderState.PAGADO||next==OrderState.CANCELADO));if(!valid)throw new BusinessException(422,"Transición de estado inválida");e.estado=next;audit("Pedidos","ESTADO",e.numero+" -> "+next.label());return order(e);}
  public PhotoResponse photo(UUID id,PhotoRequest r){Pedido p=db.get(Pedido.class,id);byte[] data;try{data=Base64.getDecoder().decode(r.base64());}catch(IllegalArgumentException e){throw new BusinessException(400,"base64 inválido");}if(data.length>5_000_000)throw new BusinessException(400,"Foto excede 5 MB");if(!"image/webp".equalsIgnoreCase(r.contentType())||!webp(data))throw new BusinessException(400,"La foto debe estar en formato WebP");PedidoFoto f=new PedidoFoto();f.pedido=p;f.filename=r.filename().replaceAll("[^a-zA-Z0-9._-]","_").replaceFirst("(?i)\\.[^.]+$","")+".webp";f.contentType="image/webp";f.content=data;p.fotos.add(f);audit("Pedidos","FOTO",p.numero);return photo(p.id,f);}
  public PedidoFoto photo(UUID orderId,UUID photoId){PedidoFoto f=db.one("select f from PedidoFoto f where f.id=:photo and f.pedido.id=:order",PedidoFoto.class,Map.of("photo",photoId,"order",orderId));if(f==null)throw new NotFoundException("Foto inexistente");return f;}
  private static boolean webp(byte[] data){return data.length>=12&&data[0]=='R'&&data[1]=='I'&&data[2]=='F'&&data[3]=='F'&&data[8]=='W'&&data[9]=='E'&&data[10]=='B'&&data[11]=='P';}
  private PhotoResponse photo(UUID orderId,PedidoFoto f){return new PhotoResponse(f.id,f.filename,f.contentType,f.createdAt,"/pedidos/"+orderId+"/fotos/"+f.id);}
  private OrderResponse order(Pedido e){List<OrderItemResponse> lines=e.items.stream().map(i->new OrderItemResponse(i.id,i.itemCatalogo==null?null:i.itemCatalogo.id,i.descripcion,i.tipo,i.cantidad,i.precioUnitario,i.descuento,i.subtotal)).toList();return new OrderResponse(e.id,e.numero,e.cliente.id,e.motovehiculo.id,e.cliente.nombre,e.motovehiculo.marca.nombre+" "+e.motovehiculo.modelo,e.motovehiculo.patente,e.documento,e.vencimiento,e.observaciones,e.descuentoGlobal,e.iva,e.estado.label(),e.total,e.createdAt,lines,e.fotos.stream().map(f->photo(e.id,f)).toList());}

  @Cacheable("brands") public List<NamedResponse> brands(boolean includeDeleted){return named("MarcaMoto",MarcaMoto.class,includeDeleted);}
  @CacheEvict(value="brands",allEntries=true) public NamedResponse createBrand(NameRequest r){MarcaMoto e=new MarcaMoto();e.nombre=r.nombre().trim();e.activo=r.activo()==null||r.activo();db.persist(e);audit("Marcas","CREAR",e.nombre);return named(e);}
  @CacheEvict(value="brands",allEntries=true) public NamedResponse updateBrand(UUID id,NameRequest r){MarcaMoto e=db.get(MarcaMoto.class,id);if(Boolean.FALSE.equals(r.activo())&&db.count("select count(m) from Motovehiculo m where m.marca.id=:id and m.activo=true and m.deletedAt is null",Map.of("id",id))>0)throw new BusinessException(409,"La marca tiene motos activas");e.nombre=r.nombre().trim();if(r.activo()!=null)e.activo=r.activo();audit("Marcas","EDITAR",e.nombre);return named(e);}
  @CacheEvict(value="brands",allEntries=true) public void deleteBrand(UUID id){MarcaMoto e=db.get(MarcaMoto.class,id);if(db.count("select count(m) from Motovehiculo m where m.marca.id=:id and m.activo=true and m.deletedAt is null",Map.of("id",id))>0)throw new BusinessException(409,"La marca tiene motos activas");deleted(e);audit("Marcas","ELIMINAR",e.nombre);}
  @Cacheable("categories") public List<NamedResponse> categories(boolean includeDeleted){return named("CategoriaCatalogo",CategoriaCatalogo.class,includeDeleted);}
  @CacheEvict(value="categories",allEntries=true) public NamedResponse createCategory(NameRequest r){CategoriaCatalogo e=new CategoriaCatalogo();e.nombre=r.nombre().trim();e.activo=r.activo()==null||r.activo();db.persist(e);audit("Categorías","CREAR",e.nombre);return named(e);}
  @CacheEvict(value="categories",allEntries=true) public NamedResponse updateCategory(UUID id,NameRequest r){CategoriaCatalogo e=db.get(CategoriaCatalogo.class,id);if(Boolean.FALSE.equals(r.activo())&&db.count("select count(i) from ItemCatalogo i where i.categoria.id=:id and i.activo=true and i.deletedAt is null",Map.of("id",id))>0)throw new BusinessException(409,"La categoría tiene ítems activos");e.nombre=r.nombre().trim();if(r.activo()!=null)e.activo=r.activo();audit("Categorías","EDITAR",e.nombre);return named(e);}
  @CacheEvict(value="categories",allEntries=true) public void deleteCategory(UUID id){CategoriaCatalogo e=db.get(CategoriaCatalogo.class,id);if(db.count("select count(i) from ItemCatalogo i where i.categoria.id=:id and i.activo=true and i.deletedAt is null",Map.of("id",id))>0)throw new BusinessException(409,"La categoría tiene ítems activos");deleted(e);audit("Categorías","ELIMINAR",e.nombre);}
  private <T extends BaseEntity> List<NamedResponse> named(String ignored,Class<T> type,boolean includeDeleted){return db.all("select e from "+type.getSimpleName()+" e where "+(includeDeleted?"1=1":"e.deletedAt is null")+" order by e.nombre",type,Map.of()).stream().map(this::named).toList();}
  private NamedResponse named(BaseEntity e){if(e instanceof MarcaMoto x)return new NamedResponse(x.id,x.nombre,x.activo,x.createdAt,x.updatedAt);CategoriaCatalogo x=(CategoriaCatalogo)e;return new NamedResponse(x.id,x.nombre,x.activo,x.createdAt,x.updatedAt);}

  public List<UserResponse> users(boolean includeDeleted){return db.all("select e from AppUser e where "+(includeDeleted?"1=1":"e.deletedAt is null")+" order by e.nombre",AppUser.class,Map.of()).stream().map(this::user).toList();}
  public UserResponse createUser(UserRequest r){if(r.password()==null)throw new BusinessException(400,"La contraseña es obligatoria");AppUser e=new AppUser();copy(r,e,true);db.persist(e);audit("Usuarios","CREAR",e.nombre);return user(e);}
  public UserResponse updateUser(UUID id,UserRequest r){AppUser e=db.get(AppUser.class,id);if(e.rol==Role.ADMINISTRACION&&Boolean.FALSE.equals(r.activo())&&admins()==1)throw new BusinessException(409,"No puede desactivarse el último administrador");copy(r,e,false);audit("Usuarios","EDITAR",e.nombre);return user(e);}
  public void deleteUser(UUID id){AppUser e=db.get(AppUser.class,id);if(e.rol==Role.ADMINISTRACION&&admins()==1)throw new BusinessException(409,"No puede eliminarse el último administrador");deleted(e);audit("Usuarios","ELIMINAR",e.email);}
  private long admins(){return db.count("select count(e) from AppUser e where e.rol=:r and e.activo=true and e.deletedAt is null",Map.of("r",Role.ADMINISTRACION));}
  private void copy(UserRequest r,AppUser e,boolean newUser){e.username=r.username().trim().toLowerCase();e.nombre=r.nombre().trim();e.email=blank(r.email());e.rol=r.rol();if(r.activo()!=null)e.activo=r.activo();if(r.password()!=null)e.passwordHash=org.springframework.security.crypto.bcrypt.BCrypt.hashpw(r.password(),org.springframework.security.crypto.bcrypt.BCrypt.gensalt());}
  UserResponse user(AppUser e){return new UserResponse(e.id,e.nombre,e.email,e.rol,e.activo,e.createdAt,e.updatedAt);}
  public List<AuditResponse> audits(String q,UUID user,String module,String action,Instant from,Instant to){Map<String,Object> ps=p();String w=" where 1=1";if(q!=null&&!q.isBlank()){w+=" and lower(e.descripcion) like :q";ps.put("q","%"+q.toLowerCase()+"%");}if(user!=null){w+=" and e.usuario.id=:u";ps.put("u",user);}if(module!=null){w+=" and e.modulo=:m";ps.put("m",module);}if(action!=null){w+=" and e.accion=:a";ps.put("a",action);}if(from!=null){w+=" and e.fecha>=:f";ps.put("f",from);}if(to!=null){w+=" and e.fecha<=:t";ps.put("t",to);}return db.all("select e from Auditoria e left join fetch e.usuario"+w+" order by e.fecha desc",Auditoria.class,ps).stream().map(e->new AuditResponse(e.id,e.fecha,e.usuario==null?"Sistema":e.usuario.nombre,e.modulo,e.accion,e.descripcion)).toList();}
  public List<ReportResponse> summary(){return List.of(new ReportResponse("Clientes",BigDecimal.valueOf(db.count("select count(e) from Cliente e where e.deletedAt is null",Map.of()))),new ReportResponse("Pedidos",BigDecimal.valueOf(db.count("select count(e) from Pedido e where e.deletedAt is null",Map.of()))),new ReportResponse("Facturado",db.all("select e from Pedido e where e.estado=:s and e.deletedAt is null",Pedido.class,Map.of("s",OrderState.PAGADO)).stream().map(x->x.total).reduce(BigDecimal.ZERO,BigDecimal::add)));}
  public List<ReportResponse> evolution(){return db.all("select e from Pedido e where e.deletedAt is null",Pedido.class,Map.of()).stream().collect(Collectors.groupingBy(x->x.createdAt.atZone(ZoneId.of("America/Argentina/Buenos_Aires")).toLocalDate().toString(),Collectors.reducing(BigDecimal.ZERO,x->x.total,BigDecimal::add))).entrySet().stream().sorted(Map.Entry.comparingByKey()).map(x->new ReportResponse(x.getKey(),x.getValue())).toList();}
  public List<ReportResponse> topItems(){return db.all("select e from Pedido e where e.deletedAt is null",Pedido.class,Map.of()).stream().flatMap(x->x.items.stream()).collect(Collectors.groupingBy(x->x.descripcion,Collectors.reducing(BigDecimal.ZERO,x->x.cantidad,BigDecimal::add))).entrySet().stream().sorted(Map.Entry.<String,BigDecimal>comparingByValue().reversed()).limit(10).map(x->new ReportResponse(x.getKey(),x.getValue())).toList();}
  public DashboardResponse dashboard(LocalDate from,LocalDate to){LocalDate start=from==null?LocalDate.now(ZoneId.of("America/Argentina/Buenos_Aires")).withDayOfMonth(1):from;LocalDate end=to==null?start.plusMonths(1).minusDays(1):to;if(end.isBefore(start))throw new BusinessException(400,"El rango de fechas es inválido");Instant since=start.atStartOfDay(ZoneOffset.UTC).toInstant();Instant until=end.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant();List<Pedido> orders=db.all("select e from Pedido e join fetch e.cliente join fetch e.motovehiculo m join fetch m.marca where e.deletedAt is null and e.createdAt>=:since and e.createdAt<:until",Pedido.class,Map.of("since",since,"until",until));long process=orders.stream().filter(x->x.estado==OrderState.EN_PROCESO).count();long approved=orders.stream().filter(x->x.estado==OrderState.APROBADO).count();long paid=orders.stream().filter(x->x.estado==OrderState.PAGADO).count();long cancelled=orders.stream().filter(x->x.estado==OrderState.CANCELADO).count();BigDecimal quoted=orders.stream().filter(x->x.estado!=OrderState.CANCELADO).map(x->x.total).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal billed=orders.stream().filter(x->x.estado==OrderState.PAGADO).map(x->x.total).reduce(BigDecimal.ZERO,BigDecimal::add);List<DashboardDayResponse> trend=orders.stream().collect(Collectors.groupingBy(x->x.createdAt.atZone(ZoneId.of("America/Argentina/Buenos_Aires")).toLocalDate(),Collectors.reducing(BigDecimal.ZERO,x->x.total,BigDecimal::add))).entrySet().stream().sorted(Map.Entry.comparingByKey()).map(x->new DashboardDayResponse(x.getKey(),x.getValue())).toList();List<DashboardOrderResponse> recent=orders.stream().sorted(Comparator.comparing((Pedido x)->x.createdAt).reversed()).limit(6).map(x->new DashboardOrderResponse(x.id,x.numero,x.cliente.nombre,x.motovehiculo.marca.nombre+" "+x.motovehiculo.modelo,x.estado.label(),x.total,x.createdAt)).toList();return new DashboardResponse(start,end,orders.size(),process,approved,paid,cancelled,quoted,billed,trend,recent);}
  private static BigDecimal money(BigDecimal value){return value.setScale(2,RoundingMode.HALF_UP);} private static String blank(String value){return value==null||value.isBlank()?null:value.trim();}
}
