package com.avianto.back;

import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import java.sql.Types;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;

enum Role { ADMINISTRACION, OPERARIO }
enum FichaState { PENDIENTE, EN_PROCESO, REVISION, TERMINADA, ENTREGADA, CANCELADA;
  static FichaState of(String v) { return switch (v) { case "Pendiente" -> PENDIENTE; case "En proceso" -> EN_PROCESO; case "En revisión", "Revisión" -> REVISION; case "Terminada" -> TERMINADA; case "Entregada" -> ENTREGADA; case "Cancelada" -> CANCELADA; default -> throw new BusinessException(422, "Estado inválido"); }; }
  String label() { return switch(this) { case PENDIENTE -> "Pendiente"; case EN_PROCESO -> "En proceso"; case REVISION -> "En revisión"; case TERMINADA -> "Terminada"; case ENTREGADA -> "Entregada"; case CANCELADA -> "Cancelada"; }; }
}
enum MotoSection { TALLER, VENTA;
  static MotoSection of(String v) { return switch (v) { case "TALLER", "Taller" -> TALLER; case "VENTA", "Venta" -> VENTA; default -> throw new BusinessException(422, "Sección de moto inválida"); }; }
  String label() { return this == TALLER ? "Taller" : "Venta"; }
}
enum MotoState { DISPONIBLE, INGRESADA_TALLER, PENDIENTE, EN_PROCESO, REVISION, TERMINADA, ENTREGADA, EN_VENTA, TRANSFERENCIA_EN_PROCESO, VENDIDA;
  static MotoState of(String v) { return switch (v) { case "Disponible", "Fuera del taller", "ACTIVA" -> DISPONIBLE; case "Ingresada Taller" -> INGRESADA_TALLER; case "Pendiente" -> PENDIENTE; case "En proceso" -> EN_PROCESO; case "En revisión", "Revisión" -> REVISION; case "Terminada" -> TERMINADA; case "Entregada" -> ENTREGADA; case "En venta" -> EN_VENTA; case "Transferencia en proceso" -> TRANSFERENCIA_EN_PROCESO; case "Vendida" -> VENDIDA; default -> throw new BusinessException(422, "Estado de moto inválido"); }; }
  String label() { return switch(this) { case DISPONIBLE -> "Disponible"; case INGRESADA_TALLER -> "Ingresada Taller"; case PENDIENTE -> "Pendiente"; case EN_PROCESO -> "En proceso"; case REVISION -> "En revisión"; case TERMINADA -> "Terminada"; case ENTREGADA -> "Entregada"; case EN_VENTA -> "En venta"; case TRANSFERENCIA_EN_PROCESO -> "Transferencia en proceso"; case VENDIDA -> "Vendida"; }; }
}
enum TrabajoState { PENDIENTE, REALIZADO, CANCELADO;
  static TrabajoState of(String v) { return switch (v) { case "Pendiente" -> PENDIENTE; case "Realizado" -> REALIZADO; case "Cancelado" -> CANCELADO; default -> throw new BusinessException(422, "Estado de trabajo inválido"); }; }
  String label() { return switch(this) { case PENDIENTE -> "Pendiente"; case REALIZADO -> "Realizado"; case CANCELADO -> "Cancelado"; }; }
}
enum PagoState { NO_PAGADO, PARCIAL, PAGADO;
  static PagoState of(String v) { return switch (v) { case "No pagado" -> NO_PAGADO; case "Parcial" -> PARCIAL; case "Pagado" -> PAGADO; default -> throw new BusinessException(422, "Estado de pago inválido"); }; }
  String label() { return switch(this) { case NO_PAGADO -> "No pagado"; case PARCIAL -> "Parcial"; case PAGADO -> "Pagado"; }; }
}
enum MedioPago { EFECTIVO, TRANSFERENCIA, DEBITO, CREDITO, MERCADO_PAGO, OTRO;
  static MedioPago of(String v) { if (v == null || v.isBlank()) return null; return switch (v) { case "Efectivo" -> EFECTIVO; case "Transferencia" -> TRANSFERENCIA; case "Débito" -> DEBITO; case "Crédito" -> CREDITO; case "Mercado Pago" -> MERCADO_PAGO; case "Otro" -> OTRO; default -> throw new BusinessException(422, "Medio de pago inválido"); }; }
  String label() { return switch(this) { case EFECTIVO -> "Efectivo"; case TRANSFERENCIA -> "Transferencia"; case DEBITO -> "Débito"; case CREDITO -> "Crédito"; case MERCADO_PAGO -> "Mercado Pago"; case OTRO -> "Otro"; }; }
}
enum RepuestoCategoria { REPUESTO, ACCESORIO;
  static RepuestoCategoria of(String v) { return switch (v) { case "Repuesto" -> REPUESTO; case "Accesorio" -> ACCESORIO; default -> throw new BusinessException(422, "Tipo de ítem inválido"); }; }
  String label() { return switch(this) { case REPUESTO -> "Repuesto"; case ACCESORIO -> "Accesorio"; }; }
}
enum RepuestoItemState { PENDIENTE_DE_PEDIR, PEDIDO, RECIBIDO, ENTREGADO, CANCELADO;
  static RepuestoItemState of(String v) { return switch (v) { case "Pendiente de pedir" -> PENDIENTE_DE_PEDIR; case "Pedido" -> PEDIDO; case "Recibido" -> RECIBIDO; case "Entregado" -> ENTREGADO; case "Cancelado" -> CANCELADO; default -> throw new BusinessException(422, "Estado de ítem inválido"); }; }
  String label() { return switch(this) { case PENDIENTE_DE_PEDIR -> "Pendiente de pedir"; case PEDIDO -> "Pedido"; case RECIBIDO -> "Recibido"; case ENTREGADO -> "Entregado"; case CANCELADO -> "Cancelado"; }; }
}
enum RepuestoPedidoState { EN_CURSO, COMPLETADO, CANCELADO;
  static RepuestoPedidoState of(String v) { return switch (v) { case "En curso" -> EN_CURSO; case "Completado" -> COMPLETADO; case "Cancelado" -> CANCELADO; default -> throw new BusinessException(422, "Estado de pedido inválido"); }; }
  String label() { return switch(this) { case EN_CURSO -> "En curso"; case COMPLETADO -> "Completado"; case CANCELADO -> "Cancelado"; }; }
}
enum RevisionState { ABIERTA, APROBADA }
enum RevisionControlState { PENDIENTE, REVISADO, NO_APLICA;
  static RevisionControlState of(String v) { return switch (v) { case "Pendiente" -> PENDIENTE; case "Revisado" -> REVISADO; case "No aplica" -> NO_APLICA; default -> throw new BusinessException(422, "Estado de control inválido"); }; }
  String label() { return switch(this) { case PENDIENTE -> "Pendiente"; case REVISADO -> "Revisado"; case NO_APLICA -> "No aplica"; }; }
}
enum VentaChecklistState { PENDIENTE, REALIZADO, NO_APLICA;
  static VentaChecklistState of(String v) { return switch (v) { case "Pendiente" -> PENDIENTE; case "Realizado" -> REALIZADO; case "No aplica" -> NO_APLICA; default -> throw new BusinessException(422, "Estado de checklist de venta inválido"); }; }
  String label() { return switch(this) { case PENDIENTE -> "Pendiente"; case REALIZADO -> "Realizado"; case NO_APLICA -> "No aplica"; }; }
}

@MappedSuperclass abstract class BaseEntity {
  @Id UUID id = UUID.randomUUID();
  @Version long version;
  @Column(name="created_at", nullable=false) Instant createdAt = Instant.now();
  @Column(name="updated_at", nullable=false) Instant updatedAt = Instant.now();
  @Column(name="deleted_at") Instant deletedAt;
  @Column(name="deleted_by") UUID deletedBy;
  @PreUpdate void updateTimestamp() { updatedAt = Instant.now(); }
}
@Entity @Table(name="app_user") class AppUser extends BaseEntity { String nombre; String username; String email; @Column(name="password_hash") String passwordHash; @Enumerated(EnumType.STRING) Role rol; boolean activo=true; }
@Entity class MarcaMoto extends BaseEntity { String nombre; boolean activo=true; }
@Entity class Cliente extends BaseEntity { String nombre; String documento; String telefono; String email; String direccion; @Column(columnDefinition="text") String observaciones; boolean activo=true; }
@Entity class Motovehiculo extends BaseEntity { @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="marca_id",nullable=false) MarcaMoto marca; String modelo; String patente; Integer anio; Integer kilometraje; @Enumerated(EnumType.STRING) MotoSection seccion; @Enumerated(EnumType.STRING) @Column(name="estado_operativo",nullable=false) MotoState estadoOperativo=MotoState.DISPONIBLE; boolean ingresada=false; @Column(name="km_ultimo_service") Integer kmUltimoService; @Column(name="fecha_ultimo_service") LocalDate fechaUltimoService; @Column(name="km_service_periodo") Integer kmServicePeriodo=5000; @Column(name="meses_service_periodo") Integer mesesServicePeriodo=6; @Column(name="service_observaciones",columnDefinition="text") String serviceObservaciones; @Column(columnDefinition="text") String observaciones; boolean activo=true; }
@Entity @Table(name="propietario_moto") class PropietarioMoto extends BaseEntity { @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="motovehiculo_id",nullable=false) Motovehiculo motovehiculo; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="cliente_id",nullable=false) Cliente cliente; @Column(name="fecha_desde") LocalDate fechaDesde; @Column(name="fecha_hasta") LocalDate fechaHasta; @Column(columnDefinition="text") String observaciones; }
@Entity @Table(name="transferencia_moto") class TransferenciaMoto extends BaseEntity { @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="motovehiculo_id",nullable=false) Motovehiculo motovehiculo; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="cliente_anterior_id",nullable=false) Cliente clienteAnterior; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="cliente_nuevo_id",nullable=false) Cliente clienteNuevo; @OneToOne(fetch=FetchType.LAZY) @JoinColumn(name="ficha_venta_id",unique=true) VentaFicha fichaVenta; @Column(name="fecha_transferencia") LocalDate fechaTransferencia; @Column(name="cita_fecha") LocalDate citaFecha; @Column(name="cita_hora") LocalTime citaHora; @Column(name="cita_lugar",length=300) String citaLugar; @Column(name="asistencia_at") Instant asistenciaAt; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="asistencia_por") AppUser asistenciaPor; @Column(name="cancelada_at") Instant canceladaAt; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="cancelada_por") AppUser canceladaPor; @Column(name="finalizada_at") Instant finalizadaAt; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="finalizada_por") AppUser finalizadaPor; @Column(columnDefinition="text") String observaciones; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="realizada_por") AppUser realizadaPor; }
@Entity @Table(name="venta_checklist_plantilla") class VentaChecklistPlantilla extends BaseEntity { @Column(length=200) String etiqueta; int orden; boolean obligatorio=true; boolean activo=true; }
@Entity @Table(name="ficha_venta") class VentaFicha extends BaseEntity { @Column(unique=true) String numero; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="motovehiculo_id",nullable=false,unique=true) Motovehiculo motovehiculo; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="vendedor_id",nullable=false) Cliente vendedor; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="comprador_id") Cliente comprador; @Column(name="finalizada_at") Instant finalizadaAt; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="finalizada_por") AppUser finalizadaPor; @OneToMany(mappedBy="fichaVenta",cascade=CascadeType.ALL,orphanRemoval=true) List<VentaFichaItem> items=new ArrayList<>(); @OneToOne(mappedBy="fichaVenta",fetch=FetchType.EAGER) TransferenciaMoto transferencia; }
@Entity @Table(name="ficha_venta_item") class VentaFichaItem { @Id UUID id=UUID.randomUUID(); @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="ficha_venta_id",nullable=false) VentaFicha fichaVenta; @Column(length=200) String etiqueta; int orden; boolean obligatorio; @Enumerated(EnumType.STRING) VentaChecklistState estado=VentaChecklistState.PENDIENTE; @Column(name="realizado_at") Instant realizadoAt; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="realizado_por") AppUser realizadoPor; @Column(name="created_at",nullable=false) Instant createdAt=Instant.now(); @Column(name="updated_at",nullable=false) Instant updatedAt=Instant.now(); @PreUpdate void updateTimestamp(){updatedAt=Instant.now();} }
@Entity class Ficha extends BaseEntity { @Column(unique=true) String numero; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="cliente_id",nullable=false) Cliente cliente; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="motovehiculo_id",nullable=false) Motovehiculo motovehiculo; LocalDate vencimiento; @Column(name="fecha_ingreso") LocalDate fechaIngreso; @Column(name="fecha_entrega_estimada") LocalDate fechaEntregaEstimada; @Column(name="fecha_entrega_real") LocalDate fechaEntregaReal; @Column(name="kilometraje_ingreso") Integer kilometrajeIngreso; @Column(columnDefinition="text") String observaciones; @Column(name="descuento_global") BigDecimal descuentoGlobal=BigDecimal.ZERO; boolean iva; @Enumerated(EnumType.STRING) FichaState estado=FichaState.PENDIENTE; @Enumerated(EnumType.STRING) @Column(name="estado_pago") PagoState estadoPago=PagoState.NO_PAGADO; BigDecimal total=BigDecimal.ZERO; @OneToMany(mappedBy="ficha",cascade=CascadeType.ALL,orphanRemoval=true) List<FichaTrabajo> trabajos=new ArrayList<>(); @OneToMany(mappedBy="ficha",cascade=CascadeType.ALL,orphanRemoval=true) List<FichaFoto> fotos=new ArrayList<>(); @OneToMany(mappedBy="ficha") List<Pago> pagos=new ArrayList<>(); }
@Entity @Table(name="ficha_trabajo") class FichaTrabajo { @Id UUID id=UUID.randomUUID(); @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="ficha_id") Ficha ficha; String descripcion; @Column(name="precio_aplicado") BigDecimal precioAplicado; BigDecimal descuento=BigDecimal.ZERO; BigDecimal subtotal=BigDecimal.ZERO; @Enumerated(EnumType.STRING) @Column(name="estado_trabajo") TrabajoState estadoTrabajo=TrabajoState.PENDIENTE; @Column(name="observacion_trabajo",columnDefinition="text") String observacionTrabajo; @Column(name="completado_at") Instant completadoAt; @Column(name="completado_por") UUID completadoPor; }
@Entity @Table(name="trabajo_catalogo") class TrabajoCatalogo extends BaseEntity { String descripcion; @Column(name="precio_base") BigDecimal precioBase; boolean activo=true; }
@Entity @Table(name="ficha_foto") class FichaFoto { @Id UUID id=UUID.randomUUID(); @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="ficha_id") Ficha ficha; String filename; @Column(name="content_type") String contentType; @JdbcTypeCode(Types.VARBINARY) byte[] content; @Column(name="created_at") Instant createdAt=Instant.now(); }
@Entity @Table(name="repuesto_pedido") class RepuestoPedido extends BaseEntity { @Column(unique=true) String numero; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="motovehiculo_id",nullable=false) Motovehiculo motovehiculo; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="cliente_id",nullable=false) Cliente cliente; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="ficha_id") Ficha ficha; LocalDate fecha; @Enumerated(EnumType.STRING) RepuestoPedidoState estado=RepuestoPedidoState.EN_CURSO; @Enumerated(EnumType.STRING) @Column(name="estado_pago") PagoState estadoPago=PagoState.NO_PAGADO; BigDecimal total=BigDecimal.ZERO; String proveedor; @Column(columnDefinition="text") String observaciones; @OneToMany(mappedBy="pedido",cascade=CascadeType.ALL,orphanRemoval=true) List<RepuestoPedidoItem> items=new ArrayList<>(); @OneToMany(mappedBy="repuestoPedido") List<Pago> pagos=new ArrayList<>(); }
@Entity @Table(name="repuesto_pedido_item") class RepuestoPedidoItem { @Id UUID id=UUID.randomUUID(); @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="repuesto_pedido_id") RepuestoPedido pedido; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="ficha_trabajo_id") FichaTrabajo fichaTrabajo; String descripcion; @Enumerated(EnumType.STRING) RepuestoCategoria tipo=RepuestoCategoria.REPUESTO; BigDecimal cantidad=BigDecimal.ONE; BigDecimal precio; BigDecimal subtotal; @Enumerated(EnumType.STRING) RepuestoItemState estado=RepuestoItemState.PENDIENTE_DE_PEDIR; @Column(columnDefinition="text") String observaciones; }
@Entity @Table(name="pago") class Pago extends BaseEntity { @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="ficha_id") Ficha ficha; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="repuesto_pedido_id") RepuestoPedido repuestoPedido; BigDecimal monto; LocalDate fecha; @Enumerated(EnumType.STRING) @Column(name="medio_pago") MedioPago medioPago; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="creado_por") AppUser creadoPor; @Column(name="anulado_at") Instant anuladoAt; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="anulado_por") AppUser anuladoPor; }
@Entity class Categoria extends BaseEntity { String nombre; boolean activo=true; }
@Entity @Table(name="control_revision") class ControlRevision extends BaseEntity { String nombre; @Column(columnDefinition="text") String descripcion; boolean obligatorio=true; int orden; boolean activo=true; @ManyToMany(fetch=FetchType.EAGER) @JoinTable(name="control_revision_categoria",joinColumns=@JoinColumn(name="control_revision_id"),inverseJoinColumns=@JoinColumn(name="categoria_id")) List<Categoria> categorias=new ArrayList<>(); }
@Entity @Table(name="revision") class Revision extends BaseEntity { @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="ficha_id",nullable=false,unique=true) Ficha ficha; @Enumerated(EnumType.STRING) RevisionState estado=RevisionState.ABIERTA; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="aprobado_por") AppUser aprobadoPor; @Column(name="aprobado_at") Instant aprobadoAt; boolean forzada; @Column(columnDefinition="text") String observacion; @OneToMany(mappedBy="revision",cascade=CascadeType.ALL,orphanRemoval=true) List<RevisionControl> controles=new ArrayList<>(); }
 @Entity @Table(name="revision_control", uniqueConstraints=@UniqueConstraint(name="ux_revision_control_revision_control", columnNames={"revision_id", "control_id"})) class RevisionControl { @Id UUID id=UUID.randomUUID(); @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="revision_id") Revision revision; @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="control_id",nullable=false) ControlRevision control; @Enumerated(EnumType.STRING) RevisionControlState estado=RevisionControlState.PENDIENTE; @Column(columnDefinition="text") String observacion; @Column(name="correccion_necesaria",columnDefinition="text") String correccionNecesaria; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="revisado_por") AppUser revisadoPor; @Column(name="revisado_at") Instant revisadoAt; }
@Entity @Table(name="service_moto") class ServiceMoto { @Id UUID id=UUID.randomUUID(); @ManyToOne(fetch=FetchType.EAGER,optional=false) @JoinColumn(name="motovehiculo_id",nullable=false) Motovehiculo motovehiculo; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="ficha_id") Ficha ficha; @Column(name="kilometraje") Integer kilometraje; LocalDate fecha; @Column(columnDefinition="text") String observaciones; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="realizado_por") AppUser realizadoPor; @Column(name="created_at") Instant createdAt=Instant.now(); }
@Entity @Table(name="refresh_token") class RefreshToken { @Id UUID id=UUID.randomUUID(); @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="user_id") AppUser user; @Column(name="token_hash") String tokenHash; @Column(name="expires_at") Instant expiresAt; @Column(name="revoked_at") Instant revokedAt; @Column(name="created_at") Instant createdAt=Instant.now(); }
@Entity @Table(name="auditoria") class Auditoria { @Id UUID id=UUID.randomUUID(); Instant fecha=Instant.now(); @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="usuario_id") AppUser usuario; String modulo; String accion; @Column(columnDefinition="text") String descripcion; }
