ALTER TABLE ficha_venta_item ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ficha_trabajo ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE repuesto_pedido_item ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE revision_control ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
